### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by Sandlayth** [sonnym/fics_web_interface#1]
Hi ! I tried to start it and then : 

```
npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! fics_web_interface@0.0.1 start: `bower --config.interactive=false install && ./node_modules/.bin/gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fics_web_interface@0.0.1 start script 'bower --config.interactive=false install && ./node_modules/.bin/gulp'.
npm ERR! This is most likely a problem with the fics_web_interface package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --config.interactive=false install && ./node_modules/.bin/gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls fics_web_interface
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kalix/documents/dev/html_css_js/fics_web_interface/npm-debug.log
```

Contents of  /home/kalix/documents/dev/html_css_js/fics_web_interface/npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.7.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart fics_web_interface@0.0.1
6 info start fics_web_interface@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info fics_web_interface@0.0.1 Failed to exec start script
9 verbose stack Error: fics_web_interface@0.0.1 start: `bower --config.interactive=false install && ./node_modules/.bin/gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid fics_web_interface@0.0.1
11 verbose cwd /home/kalix/documents/dev/html_css_js/fics_web_interface
12 error Linux 3.18.6-1-ARCH
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v0.12.0
15 error npm  v2.7.1
16 error code ELIFECYCLE
17 error fics_web_interface@0.0.1 start: `bower --config.interactive=false install && ./node_modules/.bin/gulp`
17 error Exit status 1
18 error Failed at the fics_web_interface@0.0.1 start script 'bower --config.interactive=false install && ./node_modules/.bin/gulp'.
18 error This is most likely a problem with the fics_web_interface package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     bower --config.interactive=false install && ./node_modules/.bin/gulp
18 error You can get their info via:
18 error     npm owner ls fics_web_interface
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by sonnym** [comment]
Thanks a lot for checking out the project and filing the bug report!

I suspect that the development dependencies were not installed (you can check for the existence of `node_modules/.bin/bower`.  Was there any bizarre output from `npm install`?  Could you try `npm install --ignore-shrinkwrap`?

Please let me know if that helps.  Thanks!

**Comment by Sandlayth** [comment]
I checked, the file exist.
Here is the complete output of npm start (even after the command you told me to use) : ''' http://sprunge.us/Miji '''
And, last and not least, I thank you for your good project!

**Comment by sonnym** [comment]
Thanks for the positive feedback!  That additional information helped me resolve the issue.  There was a version conflict that was not properly resolved.  It should be all good after the most recent commit.

Also, please note, it does take like ~10 seconds on my machine for the scripts to fully compile and the application to start up, so it requires a bit of patience!
